### ISSUE TITLE
Please remove all unneeded files?

### ISSUE THREAD

**Issue by goanpeca** [Kapoorlabs-CAPED/VNet#1]
Hi @kapoorlab, please remove the following files and folders and add the to the `.gitignore` file so they are ignored

[dist](https://github.com/Kapoorlabs-CAPED/VNet/tree/main/dist)
[viz_oneat.egg-info](https://github.com/Kapoorlabs-CAPED/VNet/tree/main/viz_oneat.egg-info)
[viznet.egg-info](https://github.com/Kapoorlabs-CAPED/VNet/tree/main/viznet.egg-info)
[vnet.egg-info](https://github.com/Kapoorlabs-CAPED/VNet/tree/main/vnet.egg-info)

**Comment by kapoorlab** [comment]
Hi @goanpeca, many thanks for pointing this out, this [commit](https://github.com/Kapoorlabs-CAPED/VNet/commit/983c10bbf37f8c404af6d4055a98a0fb483af889) fixes it.

**Comment by goanpeca** [comment]
@kapoorlab please remove the `licenses` folder and the `dist` folder, and make sur eto add the to the `.gitignore` file

Thanks!

**Comment by kapoorlab** [comment]
HI @goanpeca it's done in this [commit](https://github.com/Kapoorlabs-CAPED/VNet/commit/f033f146d2ae5c806aa1a5187d1d073f6a345765)

**Comment by goanpeca** [comment]
Awesome, thanks!
