### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [Kapoorlabs-CAPED/VNet#3]
Hi team, while working on https://github.com/conda-forge/staged-recipes/pull/21829, we found the following packages are imported but not liste on the requirements of the setup.py

- keras
- napari
- numpy
- tensorflow
- tifffile
- vollseg

Could this be updated and fixed for the next release?

Cheers!

**Comment by kapoorlab** [comment]
Hi @goanpeca, thank you for doing this, however the setup.py file contains oneat as a dependency and installing that package will install the other required packages [caped-ai-oneat](https://github.com/Kapoorlabs-CAPED/caped-ai-oneat/blob/main/setup.cfg) the vollseg-napari package mentioned in this link will install napari so I think we are good with keeping this file as is.

**Comment by goanpeca** [comment]
@kapoorlab even if another package pulls indirectly the needed dependencies, the source code of your package is diretcly importing those packages, hence those dependencies need to be explicitly declared in the setup.py file.

**Comment by kapoorlab** [comment]
@goanpeca I see, this [commit](https://github.com/Kapoorlabs-CAPED/VNet/commit/d219b404942b887cb7ec5d19ebfffac85bf9681f) declares explicit dependencies in setup.py file
